# REFERENCE https://github.com/pawamoy/copier-pdm/blob/master/mkdocs.yml
# REFERENCE https://squidfunk.github.io/mkdocs-material/
# REFERENCE https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

site_name: nya
repo_url: https://github.com/michaelwooley/nya
site_url: https://michaelwooley.github.io/nya
site_description: No, you're awesome. Python side.
site_author: Michael Wooley
edit_uri: edit/main/docs/
repo_name: michaelwooley/nya
copyright: Maintained by <a href="https://github.com/michaelwooley">Michael Wooley</a>.

nav:
  - Home: index.md
  - Modules: modules.md
  - Development:
    - dev/index.md
    - Contributing: dev/contributing.md
    - Dev setup: dev/setup.md
    - Boilerplate: dev/boilerplate.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/michaelwooley/nya

markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
